# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [2]:
import numpy as np

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o infinito.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [3]:
array = np.array([1,2,3,4,5])
np.abs(array)

array([1, 2, 3, 4, 5])

In [4]:
np.sign(array)

array([1, 1, 1, 1, 1])

In [5]:
np.ceil(array)

array([1., 2., 3., 4., 5.])

In [6]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [7]:
np.tanh(array)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [13]:
np.arcsin(1)

1.5707963267948966

#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [ ]:
array1 = np.random.randn(5, 5)
array1

In [ ]:
array2 = np.random.randn(5, 5)
array2

In [ ]:
np.minimum(array1, array2)

In [ ]:
np.divide(array1,array2)

In [ ]:
np.floor_divide(array1,array2)

### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [14]:
array1 = np.random.randn(5, 5)
array1

array([[ 0.95789973,  0.64428706, -0.24790806, -2.17316681,  0.28226685],
       [ 0.58098703, -1.03394493, -1.93127084,  0.7427299 ,  0.20622857],
       [-0.25842927, -0.91229936,  0.13632176,  2.00851136, -1.04615374],
       [ 0.19616959, -0.24221167,  2.16616527, -0.4047006 ,  0.43428911],
       [ 1.75689286,  0.40357253, -0.88957179,  0.33486041,  0.16633058]])

In [15]:
array2 = np.random.randn(5, 5)
array2

array([[-0.35131311, -0.49535554, -0.8486618 , -0.18380547, -0.01637298],
       [-0.89305946,  0.95040038,  1.1513234 , -1.83555985, -0.84694053],
       [-0.45291909,  0.12559019, -0.05993744, -1.56047377,  1.01792137],
       [-0.12571645, -0.44911619, -1.07457949, -0.42771603, -0.13148976],
       [-0.478751  , -1.24518616, -0.79865721,  0.47250841, -0.15990829]])

In [ ]:
# Fusión condicional
np.where(array1 < array2, array1, array2)

In [16]:
# Anidación de condiciones
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)

array([[-0.35131311, -0.49535554, -0.8486618 ,  0.        , -0.01637298],
       [-0.89305946,  0.        ,  0.        , -1.83555985, -0.84694053],
       [-0.45291909,  0.        , -0.05993744, -1.56047377,  0.        ],
       [-0.12571645, -0.44911619, -1.07457949, -0.42771603, -0.13148976],
       [-0.478751  , -1.24518616,  0.        ,  0.33486041, -0.15990829]])

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por filas</li>
<li>Valor 1: Aplicará la función por columnas</li>

In [17]:
array = np.random.randn(5, 4)
array

array([[-1.90328051,  2.040189  , -0.22306582,  1.22785358],
       [-0.31767035,  1.11186426,  1.18948663, -1.17207087],
       [ 2.43157352,  0.16144292, -0.38848553,  0.58315675],
       [ 0.34373212,  0.03830689,  0.03508825,  2.54493388],
       [-0.16986357,  0.01235314, -0.67909935, -0.44178115]])

In [18]:
# Operación global
np.sum(array)

6.424663776128876

In [19]:
# Operación por filas
np.sum(array, axis=0)

array([ 0.3844912 ,  3.36415621, -0.06607582,  2.74209219])

In [20]:
# Operación por columnas
np.sum(array, axis=1)

array([ 1.14169625,  0.81160967,  2.78768766,  2.96206112, -1.27839093])

Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [21]:
array.sum()

6.424663776128876

In [22]:
np.argmax(array)

15

In [23]:
np.argmin(array)

0

In [24]:
np.cumsum(array)

array([-1.90328051,  0.13690849, -0.08615733,  1.14169625,  0.8240259 ,
        1.93589016,  3.12537678,  1.95330592,  4.38487944,  4.54632236,
        4.15783683,  4.74099358,  5.08472569,  5.12303258,  5.15812083,
        7.7030547 ,  7.53319114,  7.54554427,  6.86644493,  6.42466378])

In [25]:
np.cumprod(array)

array([-1.90328051e+00, -3.88305196e+00,  8.66176170e-01,  1.06353751e+00,
       -3.37854340e-01, -3.75648166e-01, -4.46828469e-01,  5.23714631e-01,
        1.27345063e+00,  2.05589588e-01, -7.98685791e-02, -4.65759007e-02,
       -1.60096329e-02, -6.13279169e-04, -2.15188912e-05, -5.47641553e-05,
        9.30243470e-06,  1.14914271e-07, -7.80382068e-08,  3.44758087e-08])

In [27]:
# promedio por filas
np.mean(array, axis=0)

array([ 0.07689824,  0.67283124, -0.01321516,  0.54841844])

### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [28]:
array = np.random.randn(5, 5)
array

array([[-0.73445093, -0.65021147, -0.76441516, -0.21405503,  0.51418947],
       [-1.05715127,  1.33710069,  0.23232301, -1.22658954,  1.50883998],
       [-1.76590302, -1.14881009, -0.10082896, -1.03798693, -1.42096159],
       [ 0.17167254, -0.91204425, -1.01793522, -1.27911546,  0.44970919],
       [ 0.75861469,  0.71179527, -0.27911582,  0.39282434,  0.42949018]])

In [29]:
# Elementos mayores que 0
(array > 0).sum()

10

In [30]:
# Elementos menores que la media
(array < array.mean()).sum()

12

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [31]:
# Alguno de los elementos cumple la condición
(array == 0).any()

False

In [32]:
# Todos los elementos cumplen la condición
((array >= -2) & (array <= 2)).all()

True

### Ordenación de ndarrays

In [33]:
array = np.random.randn(5, 5)
array

array([[-2.13102875, -1.06761305, -0.83030805,  0.17976768, -0.2019556 ],
       [-1.12159893,  1.01306941, -0.41271806, -1.90462002, -0.40493551],
       [-0.48416144,  0.68155212, -0.74871426,  0.25819989, -0.42397843],
       [ 0.38651008,  0.51613255,  0.53483531,  0.81819628,  0.99145683],
       [ 0.44046444,  1.60326668, -0.89393473, -0.35316149, -0.22365739]])

In [34]:
# Datos ordenados
np.sort(array) 

array([[-2.13102875, -1.06761305, -0.83030805, -0.2019556 ,  0.17976768],
       [-1.90462002, -1.12159893, -0.41271806, -0.40493551,  1.01306941],
       [-0.74871426, -0.48416144, -0.42397843,  0.25819989,  0.68155212],
       [ 0.38651008,  0.51613255,  0.53483531,  0.81819628,  0.99145683],
       [-0.89393473, -0.35316149, -0.22365739,  0.44046444,  1.60326668]])

In [35]:
# Datos ordenados según el primer eje
np.sort(array, axis=0)

array([[-2.13102875, -1.06761305, -0.89393473, -1.90462002, -0.42397843],
       [-1.12159893,  0.51613255, -0.83030805, -0.35316149, -0.40493551],
       [-0.48416144,  0.68155212, -0.74871426,  0.17976768, -0.22365739],
       [ 0.38651008,  1.01306941, -0.41271806,  0.25819989, -0.2019556 ],
       [ 0.44046444,  1.60326668,  0.53483531,  0.81819628,  0.99145683]])

### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [36]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [37]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [38]:
np.unique(array1)

array([0, 2, 3, 5, 6])

In [39]:
np.union1d(array1, array2)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
np.in1d(array1, array2)

array([ True, False, False, False,  True,  True,  True,  True])